name: lukesyy-sync
on:
  schedule:
    - cron: '6 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lukesyy-Script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync NobyDa-Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lukesyy/jd_yun.git"
          source_branch: "main"
          destination_branch: "lukesyy"
          github_token: ${{ secrets.PAT }}
